name: Release Please

on:
  push:
    branches: ['main', 'master']
  workflow_run:
    workflows: ["Build Executables"]
    types:
      - completed
    branches: ['main', 'master']

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  upload-release-assets:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ github.event_name == 'push' && github.ref_name || github.event.workflow_run.head_branch }}
          path: artifacts
          if_no_artifact_found: warn

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -d "artifacts" ] && [ "$(ls -A artifacts)" ]; then
            for file in artifacts/*/*.zip; do
              gh release upload ${{ needs.release-please.outputs.tag_name }} "$file" --clobber
            done
          else
            echo "No artifacts found to upload"
          fi
