name: Release Please

# TODO: revert branches and paths
on:
  push:
    # branches: ['main', 'master']
    # paths:
    #   - 'get_cert.py'
    #   - 'get_cert.spec'
    #   - 'requirements.txt'
    #   - '*.md'
  pull_request:
    branches: ['main', 'master']
    paths:
      - 'get_cert.py'
      - 'get_cert.spec'
      - 'requirements.txt'
      - '*.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  upload-assets:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest successful run ID of the build workflow
          run_id=$(gh run list --workflow=build.yml --branch main --status completed --json databaseId --jq '.[0].databaseId')

          if [ -z "$run_id" ]; then
            echo "No successful build found. Exiting."
            exit 0
          fi

          # Download artifacts from the latest successful build
          gh run download $run_id

          # Check if tag_name is not empty
          if [ -z "${{ needs.release-please.outputs.tag_name }}" ]; then
            echo "No tag name provided. Exiting."
            exit 0
          fi

          # Get the list of current release assets
          existing_assets=$(gh release view ${{ needs.release-please.outputs.tag_name }} --json assets --jq '.assets[].name' 2>/dev/null)

          # Upload new artifacts that don't already exist in the release
          for file in */*.zip; do
            if [ ! -f "$file" ]; then
              echo "No zip files found. Exiting."
              exit 0
            fi
            filename=$(basename "$file")
            if ! echo "$existing_assets" | grep -q "$filename"; then
              gh release upload ${{ needs.release-please.outputs.tag_name }} "$file" --clobber
              echo "Uploaded $filename to release"
            else
              echo "Skipped $filename (already exists in release)"
            fi
          done
