name: Release Please

on:
  push:
    branches: ['main', 'master']
  workflow_run:
    workflows: ["Build Executables"]
    types:
      - completed
    branches: ['main', 'master']

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ github.event_name == 'push' && github.ref_name || github.event.workflow_run.head_branch }}
          path: artifacts
          if_no_artifact_found: fail

      - name: Wait for assets to be created
        id: wait-for-assets
        run: |
          while [ ! -d "artifacts" ] || [ -z "$(ls -A artifacts)" ]; do
            echo "Waiting for assets to be created..."
            sleep 10
          done

      - name: Upload Release Assets
        if: steps.wait-for-assets.outputs.exit_code == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -d "artifacts" ] && [ "$(ls -A artifacts)" ]; then
            for file in artifacts/*/*.zip; do
              gh release upload ${{ steps.release.outputs.tag_name }} "$file" --clobber
            done
              else
            echo "No artifacts found to upload"
          fi
